- name: Jenkins Configuration
  hosts: all
  gather_facts: true
  remote_user: ubuntu
  become: true
  tasks:
    - name: -------Jenkins Configuring Key and Repo ------
      block:
        - name: == >  Add Jenkins Key
          get_url:
            url: "https://pkg.jenkins.io/debian/jenkins.io-2023.key"
            dest: /usr/share/keyrings/jenkins-keyring.asc
            mode: 0644
            force: true
        - name:  ==> Adding Jenkins Repo 
          apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
            filename: jenkins
            state: present
            update_cache: true
    - name: Update apt packages
      apt:
        update_cache: yes
        cache_valid_time: 86400 
    - name: ---- Installing Java ----
      apt: 
        name: openjdk-11-jre
        state: present
    - name: ----Installing Jenkins ----
      apt: 
        name: jenkins
        state: present
    - name: Check if Jennkins service is running
      systemd:
        name: jenkins
        state: started
        enabled: yes
      register: jenkins_service_status

    - name: Display Jenkins service status
      debug:
        var: jenkins_service_status
    
    - name: -----!!! Getting jenkins initial password !!!!!!!
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
    - debug: msg={{jenkins_password.stdout_lines}}
         
