- name: Jenkins Configuration
  hosts: all
  gather_facts: true
  remote_user: ubuntu
  become: true
  tasks:
    - name: Key and repo
      block:
        - name: Add Jenkins Ky
          get_url:
            url: "https://pkg.jenkins.io/debian/jenkins.io-2023.key"
            dest: /usr/share/keyrings/jenkins-keyring.asc
            mode: 0644
            force: true
        - name: Add gh cli repo
          apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
            filename: jenkins
            state: present
            update_cache: true
    - name: Update apt packages
      apt:
        update_cache: yes
        cache_valid_time: 86400 
    - name: Installing Java
      apt: 
        name: openjdk-11-jre
        state: present
        #update_cache: yes
    - name: Installing Java
      apt: 
        name: jenkins
        state: present
         
