- name: Jenkins Configuration
  hosts: all
  gather_facts: true
  remote_user: ubuntu
  become: true
  tasks:
    - name: Key and repo
      block:
      - name: Add Jenkins repo using key from URL.
        deb822_repository:
          name: jenkins
          types: [deb]
          uris: "https://pkg.jenkins.io/debian-stable"
          components: [binary]
          signed_by: https://pkg.jenkins.io/debian-stable/jenkins.io.key
          state: present
          enabled: true
    - name: Installing Java
      apt: 
        name: openjdk-11-jre
        state: present
        update_cache: yes
    - name: Installing Java
      apt: 
        name: jenkins
        state: present
         
