- name: Server Docker Configuration
  hosts: all
  gather_facts: true
  remote_user: ubuntu
  become: true
  tasks:
    - name: Installing Docker Deps
      apt:
        name:
        - apt-transport-https
        - ca-certificates  
        - curl
        - software-properties-common
    - name: Add Apt signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name:  ==> Adding Docker ce  Repo 
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        filename: docker
        state: present
        update_cache: true
    - name: Installing Docker
      apt:
        name: docker-ce
    - name: add ec2-user to docker group and reset connection
      block:
        - name: start docker daemon
          systemd:
            name: docker
            state: started
            enabled: true
        - name: add ubuntu user to docker group
          user:
            name: ubuntu
            groups: docker
            append: yes
        - name: restart Docker service
          systemd:
            name: docker 
            state: restarted
        - name: Set permissions on docker.socket
          file:
            path: /var/run/docker.sock
            mode: '0666'
  